# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:CBrTNzcHRmjhnhH2qdjcWNgtBveXMmjRRIBzDJnEz5786soHVuTW52LlPF/UIhynxezGAUru8a0Xtah8ytd8rxsheoMB37i7tlMBNPpljaJ41+SOSuyErrz1Ti2+hAE8muBkDr/aJ7SR5vjwoU2ezlcyUUz87PqWN6PYIPEAe4s6jfO3go+R69VSpnE8hW59dcdP8ApG3sj2gkhvnOt7yQ+HwChxW8keMyDycIRv+StgBo5q,iv:D9R6WLYVgw6XOrk7X0bcalyqqpyH9KAt0WsR04Q64oM=,tag:UyAuB95d4M2owihhRrEOlA==,type:str]
sops:
  age:
    - recipient: age1wltuvtewtvlf4ycd2drsjnptrth7386jau8vk87wk329zur9dshscv2tka
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUjdweEhTdE1jcm43U2I4
        ZTdQUzNxd0ozRVdDb1R4WE5GRHpUSTVyaVMwClJ2Q1h0eCswNWp0ZlYzVDlIKzY1
        Zm5Na0EzRDBlMjkvNTlZTEVnV2lnT0EKLS0tIGlJK1h5SnlKM3FyTFZuVE9Yb1ZJ
        V24wVW1xemp0RTJCS3ZCaXBtWlVzT1kKNYjXVS6k5usUciezl+uEP/CbeIjAB2X1
        rBYER7GDdgdA3LzroMjHHGRDWVzrE40xPhvTBcRGQIafdbpZPtB2+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-19T21:13:09Z"
  mac: ENC[AES256_GCM,data:xBu+ahF7akLfVhUkrvVcZxfLcPO3FkDatllHzZ9y0LKdAfwXJD71JH8syPZNG8RiBzI3YMStKEqEkgPj6lqfN0p1hL/3jsgt5nngsRxwCNcF1DSsYy8jSIouGyPnTtG5c6E3VaM0C/FyfhKeMc1QCetaCGU+aI3F5u4WkNkM4pY=,iv:9I9ghTjJ/eIM5aMsJOEPOiKf4vLeU1MD1B7UyXE67xY=,tag:beXdoSsfwRDTOE92Fls9BA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
