# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Q7Q81HeHYVmcFUPK1a4pb7jMsRB0PhKSaSIw4guA6zSp092FYdY0ZA==,iv:XrQVEIMFAucfIuLsfbW4b3KlUq/g/7VWcv+iB6TigY0=,tag:+ePJ74bV69n5hFmkpqqc4A==,type:str]
sops:
  age:
    - recipient: age1wltuvtewtvlf4ycd2drsjnptrth7386jau8vk87wk329zur9dshscv2tka
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbzNBS09NbzhUNEVRaXRN
        dThkTFpxUHpReUhkWEl3aHNOMVFjMmtQbkZvCm1wVWJGeitkS2lsaThEeXk0RTBO
        em5DdWdCSlFQRExvelN4QUdNRHFLSzQKLS0tIEhISGZPbVlva1ZIeXNqUFp1U3Bw
        RnhpZWtGWW94RGppZFJ4SnlsS0xtSHcKo824tgNcFjIqrB/Y9uhkfM9kRwH05OqP
        Ruq+fzq1ZZbE/dbZZkQ5OD1q3whW6n908oeB1HLv07ad75A3KytsDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-19T23:18:39Z"
  mac: ENC[AES256_GCM,data:4qSkLPFlI4mzRQcK4K9CxjQpSppXb25JPC1t5ZoNyDa1kqYp5rbOrZww1BLP4/s1misyPyLIVN36ZP1Z23JIobObDRU0RLIdcGnHOUenc/iqhWzvqbRQTHM0LQI/kcFx2spPN9JdhMmHo2W7s+TQ5auXVbhIoHb7spa7SpKFU/A=,iv:xeS2J9f+BoaZ6pUxaslegNEtLjLnMzcsb1JgwIfvG08=,tag:tg7jkW50tyUhzVxvYGjUsw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
