# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:sYKOdkLHW1QrIcRVDd8I8xa298FrKCjWrttuDBj5CDQtmNh/ElmYVw==,iv:R0U+0F7paCTVh6UAXt+bodSiO34tjtKvrj00IFQCMCU=,tag:CBj+sExWcNV49IX+Y/W3yw==,type:str]
sops:
  age:
    - recipient: age1wltuvtewtvlf4ycd2drsjnptrth7386jau8vk87wk329zur9dshscv2tka
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRnhyMmEweUlFajRqRDhI
        dnlXMDROaitoU0dUcGxVdEVPMCtva05uQ0hFCnlZUXVqSHM0bVlrOTFjNlQ1YUdt
        YlFKYzVLaTBXQ2hXbndSVjJqRkkwbUUKLS0tIGg5WTR4dXBYVml1N1ZXM1o4bUZ0
        ZG1jWmR3Vk5aU3VjQjNmWUZjQUdlZUEKXz6UdMQPUZXcNr2T5hC/6qgeU/LkV/9p
        205cIXuI6SKwy5XZUrfVK+oaLyZ+AlOZ/cfevbhhOrCh6hL3caIdrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-20T14:40:33Z"
  mac: ENC[AES256_GCM,data:fiHOk5cbI2iLDICV7eBgFLvIghR/bQpNdtVkj+8OYU6vVvDcGVcPUdVGhNCcaJWd/purBM2wrkw3IyAvn70iq8DSCZvyrpzg7zqhtCnGmImHtTb545+LISWfPxqQ+e7D1+C32f07P91Lea9uOfGdMg9MLELA+CK/mtn2EjZ5GZU=,iv:cv8ct7x9AsWO25ER3KwMnVa16KlUqT4W3GV/ycU5Yg8=,tag:0F683PYaA70VHVIGrPNBdg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
