apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:nynlHmbDBqYeaH7rfA==,iv:u+bCg3/3o/D5UnlowuHHTuQeV6mAnWhrsvxENuW2590=,tag:vra5xhZgDr2uj5WrdHUZzQ==,type:str]
sops:
  age:
    - recipient: age1wltuvtewtvlf4ycd2drsjnptrth7386jau8vk87wk329zur9dshscv2tka
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNllnVjFEQVI1eWJLd3dj
        a0liK2lFSW9TeDJldXVSQkJpUnBJNVE5U2xzClYyME95YmJtd2d4UXFselk5VERD
        Zm9IWi9tSkdJNnRpcStDNFNRTFhrK2cKLS0tIDhSVStiNG9ST2dndGtOMlFNdU5S
        aW16MFI4S0U5QXFUdEhRSmJnbUF2QnMK5hFU35uMlPAtZxnjcM7ca9D4rAgqZH7d
        +zqHh95HfczzAyLmu/v4khvwvNoCqF/r6aO60csvc7QnH6SXG6+qKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-19T23:41:56Z"
  mac: ENC[AES256_GCM,data:mw/+O1byXVT+gErny/2OL84BerynPC04HgbIfe69A8sTUq0I4wpkrcd8LbyvvTz/U3bw2TF7+FN1rH7Mi0wz5SyKJjYmP1boyC8J9lO/hmw0ohgxvgHg2NUQyJcFZOsKOU+pNQMrzDsYH7D50mMJtZLegv/8s07NHWEMTglcXVI=,iv:knP76t3j7aDU5NYv15JVgc82VtDhWlDT+eLFeW2mYSo=,tag:wWQn9A5w3Y0yhmz5GGObIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
