apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:sveaboStXc2McScZYGM1rz3Gz3hF6a3/j7vovmUhIV7AT9drvzgYIg9l3aEqiQw9N8wX/YavFAy3AmCAdbI0NAK73uq41MGj5/Q=,iv:3wpzZM1sYuNtDyTVHHCuVpSqservH2WYj10ZijWUdvA=,tag:VMIJVY4c1fuJS49dLeeaEg==,type:str]
sops:
  age:
    - recipient: age1wltuvtewtvlf4ycd2drsjnptrth7386jau8vk87wk329zur9dshscv2tka
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcWpzU3VaRjFNWkw3dlVx
        MGRsd3pBQTNWenl2Y1pBcnh1MTg1ZHNDZ2o4CitXL3lSMGhENnFMQ1NIaE1pblZr
        U05KMVdHUFVjWTM2NE9GREJ5UmVqZ2sKLS0tIHdhWksyV3pGTTB1cmFCaGhZUmFC
        ZGIyNEJHSDFTVFdBTDZKdzJCSlFoM1UK0M9vNT4vkj9KoIuV63NuKXgopaUQtST1
        uzcjINfGByyv2XRqxkSWXdtEPq8iPUNPpsuZgifHY6XBRHivlXun5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-19T21:13:08Z"
  mac: ENC[AES256_GCM,data:g7WVBMFUxvTEZT3vNXt//gcnnwvDxsix0W4mLoEOjSVmpoCxeeZHLYS8tcoSVpjokUeYxpzkggVTBaUuViKfKnsvyOiWV7iYnuvRPzkkBdhw6/Xzyrn65JM8xDhE4OAG5xQBV2O+H/5VvUGtf4qO34m5Tmr90AYgeQ7pcbfo54c=,iv:paFUI3hasHaqFdsU/NhaAqOBhklnL/wN6LQ8t7dyHq8=,tag:e5OHvIyDMuX7+6Tn9L3Vbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
